version: 2
jobs:
  build:
    working_directory: /usr/src/app
    docker:
      - image: banian/node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Fixture dependencies
      - run:
          name: Website Deps
          command: |
            cd fixtures/website/nuxtjs.org
            yarn

      # Benchmark
      - run:
          name: Benchmark
          command: |
            mkdir -p benchmarks
            yarn benchmark

      # Upload artifacts
      - store_artifacts:
          path: benchmarks
